### ISSUE TITLE
Is poison ~> 3.0.0 really required?

### ISSUE THREAD

**Issue by kerryb** [slashdotdash/strava#12]
I tried adding strava to a new Phoenix project, and mix dependency resolution failed:

    Failed to use "poison" (versions 3.0.0 and 3.1.0) because
      deps/strava/mix.exs requires ~> 3.0
      phoenix (version 1.2.1) requires ~> 1.5 or ~> 2.0

I tried relaxing the requirement to `>= 2.0.0` and from some very limited testing it still seems to work.

Alternatively is there something I'm missing that I could do to avoid the clash?

**Comment by slashdotdash** [comment]
You can use the `override` flag in your `mix.exs` file to force the latest Poison version. It works fine with Phoenix too.

```elixir
defp deps do
  [{:poison, "~> 3.1", override: true}]
end
```
