### ISSUE TITLE
Segment.explore return type

### ISSUE THREAD

**Issue by jsparling** [slashdotdash/strava#22]
The Strava `explore` endpoint returns a subset of the Segment attributes that the `retrieve` endpoint returns, but in the elixir wrapper, they both return a `Strava.Segment`

https://developers.strava.com/docs/reference/#api-Segments-exploreSegments
vs
https://developers.strava.com/docs/reference/#api-Segments-getSegmentById

Should the segment#explore function return a new type? (SegmentSummary?)
https://github.com/slashdotdash/strava/blob/master/lib/strava/segment.ex#L166

**Comment by jsparling** [comment]
This PR https://github.com/slashdotdash/strava/pull/23 seems like a reasonable middle ground

**Comment by slashdotdash** [comment]
Closed by #25.
