### ISSUE TITLE
Time fields should respect timezone

### ISSUE THREAD

**Issue by et** [slashdotdash/strava#8]
There's no way to get the original timezone of something like `Activity.start_date` since they're parsed into `NaiveDateTime`s which drops the timezone.

**Comment by slashdotdash** [comment]
The Strava API uses ISO 8601 for all date/times which doesn't contain a timezone. Hence why they are converted to `NaiveDateTime`. 

The API provides a separate [timezone](http://strava.github.io/api/v3/activities/) field for an activity start date. 

This is available as `Strava.Activity.timezone`, a string (e.g. "(GMT-08:00) America/Los_Angeles").
